services:
  nginx:
    depends_on:
      - api
    build:
        context: .
        dockerfile: Dockerfile.nginx
    image: danel592/dtse-test-task:nginx-worker
    ports: ["8080:8080"]
    networks:
      - back-tier
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: ./env/.env
    image: danel592/dtse-test-task:api
    ports: ["8000:8000"]
    expose: ["8000"]
    networks:
      - back-tier
    

networks:
  back-tier:
