
name: dtse test task ci/cd

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  # Tests are executed before new compose build
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test, then build
        run: docker compose build 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images
        run: docker compose push
        
  # Pulls images, copies compose file with .env file, runs all
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Copy compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose.yml
          target: /app/
          pre-script: mkdir -p /app
      - name:  Create .env, run
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /app/env
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            cd /app
            touch env/.env
            docker compose pull
            docker compose up -d --remove-orphans
            







        
  
